import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Iceberg } from "next/font/google";
import "./globals.css";
import { ClientProviders } from "@/components/providers/ClientProviders";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "800"],
  variable: "--font-inter",
});

const iceberg = Iceberg({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-iceberg",
});

export const metadata: Metadata = {
  title: "NudgeUp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${iceberg.variable}`}>
        <ClientProviders>
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}

